### PR TITLE
Found that none of the buttons used their second argument. Removed it.

### PR DESCRIPTION
**Pull request by Rovanion**
Snabb sak jag gjorde igår kväll. Till mitt försvar var mitt sinne inte i ett tillstånd man kunde uppfinna hjulet i så då kan man lika gärna göra något trivialt.

### CODE REVIEW

**Comment by hansfilipelo** [comment]
Colors and temperature data that loads on master does not seem to load on this branch. Is this correct?

**Comment by Rovanion** [comment]
Mangel changed the behaviour so that it loads nothing by default and you have to actively choose a type of data to display. I have not changed that behaviour.

**Review by MangeI89 — COMMENTED** [review]
Temperatur-knappen har regn-bakgrund

**Review by majil334 — APPROVED** [review]
Efter merge fungerar det som det ska

**Pull request merged**
