### PR TITLE
Css its now or never edition

### PR DESCRIPTION
**Pull request by Rovanion**

### CODE REVIEW

**Comment by hansfilipelo** [comment]
Can't seem to exit the about-page in any way.

**Comment by Rovanion** [comment]
Yup, that's right. I'll see what I can do.

**Comment by hansfilipelo** [comment]
Also my month-slider sinks into the bottom of the window in both Opera and Chrome: 
 
skarmavbild 2016-12-12 kl 22 46 04

**Comment by Rovanion** [comment]
Floats suger. Slänger skiten i en tabell för fan. Synd bara att tabeller suger på sitt egna lilla sätt.

**Comment by Rovanion** [comment]
Sådär @hansfilipelo, nu är det tabulerat.

**Review by hansfilipelo — APPROVED** [review]

**Pull request merged**
